name: Deploy Website
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: add-mask
        run: echo "::add-mask::${{ secrets.SURGE_EMAIL }}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Intall Surge
        run: npm i -g surge
      - name: Deploy
        run: surge dist batch-acquisition-recycle-invoice.surge.sh --token ${{ secrets.SURGE_TOKEN }}
